import { CategoryAvatarProps } from "@/types";
import {
  CoffeeOutlined,
  ShoppingOutlined,
  GlobalOutlined,
  ThunderboltOutlined,
  HeartOutlined,
  RiseOutlined,
  BankOutlined,
  DollarOutlined,
  WalletOutlined,
  GiftOutlined,
  ShoppingCartOutlined,
  PlayCircleOutlined,
  MedicineBoxOutlined,
  BookOutlined,
  CarOutlined,
  QuestionCircleOutlined,
} from "@ant-design/icons";

export const categoryMap: Record<string, CategoryAvatarProps> = {
  food: { icon: <CoffeeOutlined />, color: "#ff9c6e" },
  clothes: { icon: <ShoppingOutlined />, color: "#ff85c0" },
  "online subscription": { icon: <GlobalOutlined />, color: "#597ef7" },
  recharge: { icon: <ThunderboltOutlined />, color: "#ffd666" },
  donation: { icon: <HeartOutlined />, color: "#ff7875" },
  interest: { icon: <RiseOutlined />, color: "#95de64" },
  salary: { icon: <BankOutlined />, color: "#b37feb" },
  profit: { icon: <DollarOutlined />, color: "#73d13d" },
  cash: { icon: <WalletOutlined />, color: "#87e8de" },
  gift: { icon: <GiftOutlined />, color: "#ffadd2" },
  groceries: { icon: <ShoppingCartOutlined />, color: "#ffc069" },
  entertainment: { icon: <PlayCircleOutlined />, color: "#b37feb" },
  health: { icon: <MedicineBoxOutlined />, color: "#ff7875" },
  education: { icon: <BookOutlined />, color: "#69c0ff" },
  transport: { icon: <CarOutlined />, color: "#95de64" },
  other: { icon: <QuestionCircleOutlined />, color: "#bfbfbf" },
};

export const categories = [
  "Food",
  "Clothes",
  "Online Subscription",
  "Recharge",
  "Donation",
  "Interest",
  "Salary",
  "Profit",
  "Cash",
  "Gift",
  "Groceries",
  "Entertainment",
  "Health",
  "Education",
  "Transport",
  "Other",
];
